### ISSUE TITLE
CSS实现激活状态环形圈

### ISSUE THREAD

**Issue by powerdong** [powerdong/myProblems#24]
![3fT4OI.png](https://s2.ax1x.com/2020/03/03/3fT4OI.png)

```css
.active{
  width: 7px;
  height: 7px;
  border-radius: 50%;
  background-color: #4370FE;
  border: 2px solid #fff;
  box-shadow: 0 0 0 1px #4370FE;
}
```
